config/routes.rb
TwitterForZombies::Application.routes.draw do
  

  resources :zombies 

  match 'editrole',   to: 'roles#addrole', via: :get
  match 'editrole', to: 'roles#transact', via: :put
  match 'deleterole', to: 'roles#deleterole', via: :get
  match 'deleterole', to: 'roles#delete', via: :delete

  root :to => 'zombies#index'

  

end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id         :integer          not null, primary key
#  zombie_id  :integer
#  role_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Assignment < ActiveRecord::Base
  attr_accessible :role_id, :zombie_id
  belongs_to :zombie
  belongs_to :role
end

app/models/brain.rb
# == Schema Information
#
# Table name: brains
#
#  id         :integer          not null, primary key
#  zombie_id  :integer
#  status     :string(255)
#  flavour    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Brain < ActiveRecord::Base
  attr_accessible :flavour, :status, :zombie_id
  belongs_to :zombie
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Role < ActiveRecord::Base
  attr_accessible :title
  has_many :assignments, dependent: :destroy
  has_many :zombies, through: :assignments
end

app/models/zombie.rb
# == Schema Information
#
# Table name: zombies
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  bio        :text
#  age        :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  rotting    :boolean
#  email      :string(255)
#

class Zombie < ActiveRecord::Base
  attr_accessible :age, :bio, :name

  has_many :assignments
  has_many :roles, through: :assignments

  has_one :brain, dependent: :destroy

  scope :rotting, where(rotting: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_filter :remaining, :current_roles

	def remaining
		@zombie = Zombie.find(params[:format]) 
		if @zombie.roles != []
			@remaining = Role.where('title not in (?)',@zombie.roles.map { |role| "#{role.title}" } )
		else
			@remaining = Role.all
		end
	end
	
	def addrole

	end
	def current_roles
		@current = @zombie.roles
	end

  def transact  	  	
	  @zombie.roles << Role.where('title in (?)', params[:select_role])
  	flash[:success] = "Successfully added roles: #{join(params[:select_role])}"
  	redirect_to @zombie	  
  end

  def deleterole  	
  	
  end

  def delete
  	@zombie.roles.delete(Role.where('title in (?)', params[:select_role]))
  	flash[:success] = "Successfully deleted roles: #{join(params[:select_role])}"
  	redirect_to @zombie
  end

  def show
  end

  def join(text)
  	text.map { |role| "#{role}" }.join(',')
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.includes(:brain).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    if !Zombie.exists?(params[:id])
      redirect_to new_zombie_path
      flash[:error] = "User not found"
    else
      @zombie = Zombie.find(params[:id])
      @roles = @zombie.roles.map { |role| "#{role.title}"}
      if @roles == []
        @roles_choice = Role.all
      else
        @roles_choice = Role.where('title not in (?)',@roles)
      end
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @zombie }
      end
    end
  end

  

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        flash[:success] = 'Zombie was successfully created.'
        format.html { redirect_to @zombie }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        flash[:success] ='Zombie was successfully updated.'
        format.html { redirect_to @zombie }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterForZombies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = "container">
		<% flash.each do | key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>

	</div>

<%= yield %>

</body>
</html>

app/views/partials/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/addrole.html.erb
<% if @current != [] %>
	<h3> Current roles</h3>

	<%= @current.map { |role| "#{role.title}"}.join(',') %> 
	<br>
	<hr style="width:90%">
<% end %>
<h3>Remaining</h3>




<%= form_tag editrole_path(@zombie), :method => :put do %>
	<ul>
			<% for role in @remaining %>
			<li>
				<%= check_box_tag("select_role[]",role.title) %>
				<%= role.title %>
			</li>	
			<% end %>			
	</ul>
	<%= submit_tag "Add Role" %>
	<br>
	<%= link_to "Delete role", deleterole_path(@zombie) %>
<% end %>

app/views/roles/deleterole.html.erb
<%= form_tag deleterole_path(@zombie), :method => :delete do %>
	<ul>
	<% for role in @current %>
		<li>
		<%= check_box_tag('select_role[]', role.title) %>
		<%= role.title %>		
		</li>		
	<% end %>
	</ul>
	<%= submit_tag "Remove roles" %>
<% end %>

app/views/zombies/_add_role.html.erb
<%= form_tag addrole_zombie_path, :method => 'put' do %>
<h3>Possible Roles!</h3>
<p>Upgrade your zombie by training in one of the following roles</p>
	<ul>
		<% @roles_choice.each do |choice| %>
		<li>
			<%= check_box_tag('select_roles[]',"#{choice.title}",false, class: "#{choice.title}") + "#{choice.title}" %><br>
			
		<% end %>	
		</li>
		<br>
		<%= submit_tag "Add role" %>
	</ul>

<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'partials/form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Brain Flavour</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.name %></td>
    <% if zombie.brain %>
      <td><%= zombie.brain.flavour %></td>
    <% else %>
      <td></td>  
    <% end %>    
    <td><%= zombie.age %><td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) + ' ' %></td>
    <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'partials/form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @zombie.bio %>
</p>

<p>
  <b>Age:</b>
  <%= @zombie.age %>
</p>

<p>
	<% if @roles != [] %>
		<b>Current Roles:</b>
		<%= @roles.join(',') %>
	<% end %>
</p>

<% if @zombie.brain %>
	<b>Brain:</b>
	<% if @zombie.brain.status %>
		<p>Brain is <%= "#{@zombie.brain.status.downcase}" %></p>
	<% end %>
	<% if @zombie.brain.flavour %>
		<p>Brain tastes like <%= "#{@zombie.brain.flavour.downcase}" %></p>
	<% end %>
<% end %>

<%= link_to 'Edit role', editrole_path(@zombie) %> |





<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>